JournalSystemMVC/Controllers/MedicalRecordsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JournalSystemMVC.DataAccessLayer;
using JournalSystemMVC.Models;
using JournalSystemMVC.Models.Medicine;
using EntityState = System.Data.Entity.EntityState;

namespace JournalSystemMVC.Controllers
{
    public class MedicalRecordsController : Controller
    {

        private readonly IMedicineRepository _medicineRepository;

        public MedicalRecordsController()
        {
            _medicineRepository = new MedicineRepository(new ApplicationDbContext());
        }

        public MedicalRecordsController(MedicineRepository medicineRepository)
        {
            _medicineRepository = medicineRepository;
        }
        
        public ActionResult Index()
        {
            return View(_medicineRepository.GetMedicalRecords());
        }
        
        public ActionResult Details(int id)
        {
            MedicalRecord medicalRecord = _medicineRepository.GetMedicalRecordById(id);
            if (medicalRecord == null)
            {
                return HttpNotFound();
            }
            return View(medicalRecord);
        }
        
        public ActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MedicalRecordId,Weight,Height,WaistLine,Created")] MedicalRecord medicalRecord)
        {
            if (ModelState.IsValid)
            {
                _medicineRepository.AddMedicalRecord(medicalRecord);
                _medicineRepository.Save();
                return RedirectToAction("Index");
            }

            return View(medicalRecord);
        }
        
        public ActionResult Edit(int id)
        {
            MedicalRecord medicalRecord = _medicineRepository.GetMedicalRecordById(id);
            if (medicalRecord == null)
            {
                return HttpNotFound();
            }
            return View(medicalRecord);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MedicalRecordId,Weight,Height,WaistLine,Created")] MedicalRecord medicalRecord)
        {
            if (ModelState.IsValid)
            {
                _medicineRepository.EditMedicalRecord(medicalRecord);
                _medicineRepository.Save();
                return RedirectToAction("Index");
            }
            return View(medicalRecord);
        }
        
        public ActionResult Delete(int id)
        {
            MedicalRecord medicalRecord = _medicineRepository.GetMedicalRecordById(id);
            if (medicalRecord == null)
            {
                return HttpNotFound();
            }
            return View(medicalRecord);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _medicineRepository.DeleteMedicalRecord(id);
            _medicineRepository.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _medicineRepository.Dispose();
            base.Dispose(disposing);
        }
    }
}

JournalSystemMVC/Views/Shared/_AddressPartialView.cshtml
@model JournalSystemMVC.Models.Address

<div>
    <h4>Address</h4>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

    </dl>
</div>

JournalSystemMVC/Views/Shared/_ContactInformationPartial.cshtml
@model JournalSystemMVC.Models.ContactInformation

<div>
        <h4>ContactInformation</h4>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PhoneNumber)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
        </dl>
</div>

JournalSystemMVC/Views/Shared/_EditAddressPartial.cshtml
@model JournalSystemMVC.Models.Address

    
    <div class="form-horizontal">
        <h4>Address</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AddressId)

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

JournalSystemMVC/Views/Shared/_EditContactInformationPartial.cshtml
@model JournalSystemMVC.Models.ContactInformation
    
    <div class="form-horizontal">
        <h4>ContactInformation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ContactInformationId)

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

JournalSystemMVC/Views/Shared/_JournalEntriesPartial.cshtml
@model IEnumerable<JournalSystemMVC.Models.ResidentData.JournalEntry>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EntryText)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EntryDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EntryText)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EntryDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.JournalEntryId }) |
            @Html.ActionLink("Details", "Details", new { id=item.JournalEntryId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.JournalEntryId })
        </td>
    </tr>
}

</table>

JournalSystemMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hugin and Munin journal system", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Employees","Index", "Employees")</li>
                    <li>@Html.ActionLink("Residents", "Index", "Residents")</li>
                    <li>@Html.ActionLink("Journals", "Index", "Journals")</li>
                    <li>@Html.ActionLink("Medical records", "Index", "MedicalRecords")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Journal System</p>
    </footer>
</div>

    <script src="https://fb.me/react-0.14.0.min.js"></script>
    <script src="https://fb.me/react-dom-0.14.0.min.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/ajax")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/sitescripts")
    @Scripts.Render("~/bundles/reactscripts")
    @Scripts.Render("~/bundles/statistics")
    @Scripts.Render("~/bundles/nvd3scripts")
    @RenderSection("scripts", required: false)
</body>
</html>

JournalSystemMVC/Views/Shared/_LoginRequest.cshtml
Please login first.