JournalSystemMVC/Models/Statistics/Answer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using JournalSystemMVC.Models.People;

namespace JournalSystemMVC.Models.Statistics
{
    // Response to question that provides 
    public class Answer
    {
        [Key]
        public int ResponseId { get; set; }
        [ForeignKey("Question")]
        [ScriptIgnore]
        public int QuestionId { get; set; }
        [ForeignKey("Employee")]
        public int EmployeeId { get; set; }
        [ForeignKey("Resident")]
        public int ResidentId { get; set; }

        public int Score { get; set; }
        public DateTime ResponseDate { get; set; }
        [ScriptIgnore]
        public Question Question { get; set; }
        public Employee Employee { get; set; }
        public Resident Resident { get; set; }
    }
}

JournalSystemMVC/Models/Statistics/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using JournalSystemMVC.Models.ModelValidationAttributes;

namespace JournalSystemMVC.Models.Statistics
{
    public class Question
    {
        [Key]
        public int QuestionId { get; set; }
        [ForeignKey("QuestionForm")]
        public int QuestionFormId { get; set; }
        [StringLengthValidation(Minimum = 6, Maximum = 80)]
        public string QuestionText { get; set; }

        public virtual ICollection<Answer> Answers { get; set; }
        public QuestionForm QuestionForm { get; set; }
    }
}

JournalSystemMVC/Models/Statistics/QuestionForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using JournalSystemMVC.Models.CustomModelAttributes;
using JournalSystemMVC.Models.ModelValidationAttributes;
using JournalSystemMVC.Models.People;

namespace JournalSystemMVC.Models.Statistics
{
    public class QuestionForm
    {
        [Key]
        public int QuestionnaireId { get; set; }

        [Required]
        [StringLengthValidation(Minimum = 2, Maximum = 60)]
        public string Title { get; set; }

        [StringLengthValidation(Minimum = 2, Maximum = 140)]
        public string Description { get; set; }
        
        public virtual ICollection<Question> Questions { get; set; }
    }
}

JournalSystemMVC/Models/Statistics/Scale.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace JournalSystemMVC.Models.Statistics
{
    public class Scale
    {
        [Key]
        public int ScaleId { get; set; }
        [ForeignKey("Questionnaire")]
        public int QuestionnaireId { get; set; }

        [Required]
        [StringLength(30, MinimumLength = 6, ErrorMessage = "Your question must be between 6 and 30 characters.")]
        public string Question { get; set; }

        [Range(1, 5, ErrorMessage = "The score must be between equal to or between 1 and 5")]
        public int? Score { get; set; }

        public QuestionForm Questionnaire { get; set; }
    }
}

JournalSystemMVC/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Web.Services;
using JournalSystemMVC.DataAccessLayer;
using JournalSystemMVC.DataTransferObjects;
using JournalSystemMVC.Models;
using JournalSystemMVC.Models.Statistics;
using JournalSystemMVC.Models.ViewModels;
using JournalSystemMVC.Models.People;

namespace JournalSystemMVC.Controllers
{
    public class StatisticsController : Controller
    {
        private readonly IQuestionFormRepository _questionFormRepository;
        private readonly IResidentRepository _residentRepository;

        public StatisticsController(IQuestionFormRepository questionFormRepository, IResidentRepository residentRepository)
        {
            _questionFormRepository = questionFormRepository;
            _residentRepository = residentRepository;
        }

        public StatisticsController()
        {
            ApplicationDbContext context = new ApplicationDbContext();
            _questionFormRepository = new QuestionFormRepository(context);
            _residentRepository = new ResidentRepository(context);
        }

        // GET: Statistics
        public ActionResult Index()
        {
           // ViewBag.json = GetQuestionData(1003).ToString();
            return View();
        }

        public ActionResult DisplayQuestionFormData()
        {
            ApplicationDbContext context = new ApplicationDbContext();
            ViewBag.QuestionFormId = new SelectList(context.QuestionForms, "QuestionnaireId", "Title");
            ViewBag.ResidentId = new SelectList(context.Residents, "ResidentId", "getFullName");
            return View();
        }
        
        // Returns 25 most recently answered questions
        // TODO: Allow manual selection of number of returned answers
        [HttpGet]
        public JsonResult GetQuestionData(int id, int residentId)
        {
            JavaScriptSerializer serializer = new JavaScriptSerializer();
            StatisticsDto dataDto = new StatisticsDto();
            List<Answer> answers = new List<Answer>(); 
            Question question = _questionFormRepository.GetQuestionById(id, residentId);

            dataDto.QuestionText = question.QuestionText;

            string json = "";

            if (question.Answers != null)
            {
                answers = question.Answers.ToList();

                
                for (int i = 0; i <= 25; i++)
                {
                    AnswerDto answerDto = new AnswerDto()
                    {
                        y = answers[i].Score,
                        x = answers[i].ResponseDate
                    };
                    dataDto.Answers.Add(answerDto);
                }
                dataDto.Answers.Sort((x, y) => DateTime.Compare(x.x, y.x));
                json = serializer.Serialize(dataDto);
            }
            else
            {
                json = "No data found.";
            }
            
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetQuestionList(int questionFormId)
        {
            String json = "";
            QuestionListDto questionIdList = new QuestionListDto();
            List<Question> questions = _questionFormRepository.GetQuestionsByQuestionFormId(questionFormId).ToList();
            JavaScriptSerializer serializer = new JavaScriptSerializer();

            for (int i = 0; i < questions.Count; i++)
            {
                questionIdList.QuestionIds.Add(questions[i].QuestionId);
            }

            json = serializer.Serialize(questionIdList);

            return Json(json, JsonRequestBehavior.AllowGet);
        }
    }    
}

JournalSystemMVC/Views/Statistics/DisplayQuestionFormData.cshtml
@{
    ViewBag.Title = "DisplayQuestionFormData";
}

<style>
    text {
        font: 12px sans-serif;
    }

    svg {
        display: block;
    }

     #chart1, #chart2, svg {
        height: 250px;
        width: 100%;
    }
</style>

<h2>DisplayQuestionFormData</h2>
<div id="chartOptions">
    @Html.DropDownList("QuestionFormId", null, htmlAttributes: new { @class = "form-control"})
    @Html.DropDownList("ResidentId", null, htmlAttributes: new { @class = "form-control" })
    <button type="button" id="updateBtn" onclick="updateCharts();">Update chart selection</button>
</div>

<div id="chart2">

</div>

@section scripts {
    <script type="text/javascript">
        //createQuestionGraph();
        createQuestionLineChart(1, 2);
        createQuestionLineChart(2, 2);
        createQuestionLineChart(3, 2);
    </script>
    <script type="text/javascript">
        function updateCharts() {
            
            var questionFormId = $('#QuestionFormId').val();
            var residentId = $('#ResidentId').val();

            console.log("It works " + questionFormId + " " + residentId);

            $.ajax({
                url: '@Url.Action("GetQuestionList", "Statistics")',
                data: { questionFormId },
                success: function (data) {
                    document.getElementById("chart2").innerHTML = "";
                    var questionIds = JSON.parse(data);

                    var i, questionId;
                    for (i = 0; i < questionIds.QuestionIds.length; i++) {
                        questionId = questionIds.QuestionIds[i];
                        createQuestionLineChart(questionId, residentId);
                    }
                }
            });

        }
    </script>
}

JournalSystemMVC/Views/Statistics/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


<style>
    text {
        font: 12px sans-serif;
    }

    svg {
        display: block;
    }

    html, body, #chart1, #chart2, svg {
        margin: 0px;
        padding: 0px;
        height: 250px;
        width: 100%;
    }
</style>



<div id="chart1">
    <svg></svg>
</div>


<div style="position:absolute; top: 0; left: 0;">
    <button onclick="randomizeFillOpacity();">Randomize fill opacity</button>
    <button onclick="expandLegend();">Expand/Contract Legend</button>
    <script>
        var expandLegend = function() {
            var exp = chart.legend.expanded();
            chart.legend.expanded(!exp);
            chart.update();
        }
    </script>
</div>
<div id="chart2"></div>


<div>@ViewBag.json</div>
<div id="testData"></div>

@section scripts {

    <script type="text/javascript">
        historicalBarChart = [
            {
                key: "Cumulative Return",
                values: [
                    {
                        "label": "Peter Svidler",
                        "value": 4.5
                    },
                    {
                        "label": "Magnus Carlsen",
                        "value": 2.1
                    },
                    {
                        "label": "Garry Kasparov",
                        "value": 3.5
                    },
                    {
                        "label": "Sergey Karjakin",
                        "value": 4
                    },
                    {
                        "label": "Veselin Topalov",
                        "value": 2.6
                    },
                    {
                        "label": "Mikhail Tal",
                        "value": 4
                    }
                ]
            }
        ];
        nv.addGraph(function() {
            var chart = nv.models.discreteBarChart()
                .x(function(d) { return d.label })
                .y(function(d) { return d.value })
                .staggerLabels(true)
                //.staggerLabels(historicalBarChart[0].values.length > 8)
                .showValues(true)
                .duration(250);
            d3.select('#chart1 svg')
                .datum(historicalBarChart)
                .call(chart);
            nv.utils.windowResize(chart.update);
            return chart;
        });
    </script>

    <script>
        function getQuestionData(userId, callback) {
           $.ajax({
                type: 'GET',
                url: 'GetQuestionData',
                data: { id: 1003 },
                dataType: 'application/json',
                success: callback,
                error: function() {
                    alert('Error during AJAX request');
                }
            });
        }

        function randomDate(start, i) {
            return new Date(start.getTime() + i);
        }

        // Wrapping in nv.addGraph allows for '0 timeout render', stores rendered charts in nv.graphs, and may do more in the future... it's NOT required
        var chart;
        var data;
        var randomizeFillOpacity = function() {
            var rand = Math.random(0, 1);
            for (var i = 0; i < 100; i++) { // modify sine amplitude
                data[4].values[i].y = Math.sin(i / (5 + rand)) * .4 * rand - .25;
            }
            data[4].fillOpacity = rand;
            chart.update();
        };

        nv.addGraph(function() {
            chart = nv.models.lineChart()
                .options({
                    duration: 300,
                    useInteractiveGuideline: true
                });
            // chart sub-models (ie. xAxis, yAxis, etc) when accessed directly, return themselves, not the parent chart, so need to chain separately
            chart.xAxis
                .axisLabel("Date (s)")
                .tickFormat(function(d) { return d3.time.format('%b %d %Y')(new Date(d)); })
                .staggerLabels(true);
            chart.yAxis
                .axisLabel('Score (v)')
                .tickFormat(function(d) {
                    if (d == null) {
                        return 'N/A';
                    }
                    return d3.format(',.2f')(d);
                });
            data = residentData();
            d3.select('#chart2').append('svg')
                .datum(data)
                .call(chart);
            nv.utils.windowResize(chart.update);
            debugger;
            return chart;
        });

        function residentData() {
          //  getQuestionData(1003, function (data) {
            var scores = [];
            //var answerList = $.getJSON("Statistics/GetQuestionData");
            getQuestionData(1003, function (data) {
                console.log("Hello from callback");
                var answerList = data;
            });
            
            console.log("Hello");

            //      for (var i = 0; i <50; i++) {
            //          scores.push({ x: randomDate(new Date(2012, 0, 1), i*86400000), y: Math.random() * (5 - 1) + 1 });
            //      }

            //for (var i = 0; i < answerList.Answers.length; i++) {
            for (var i = 0; i < 50; i++) {
                //var answer = answerList.Answers[i];
                //var dateValue = answerList[i].Answers.y;
                //var formattedDate = new Date(parseInt(dateValue.replace("/Date(", "").replace(")/", ""), 10));
                //var score = answerlist.Answers[i].[x];
                scores.push({ x: 2, y: new Date(2012, 0, 1) });
            }

            return [
                {
                    area: true,
                    values: scores,
                    key: "Question 1 scores",
                    color: "#ff7f0e",
                    strokeWidth: 5
                }
            ];

           // });
        }
    </script>

    <script>
/*
        function randomDate(start, i) {
            return new Date(start.getTime() + i);
        }

        // Wrapping in nv.addGraph allows for '0 timeout render', stores rendered charts in nv.graphs, and may do more in the future... it's NOT required
        var chart;
        var data;
        var randomizeFillOpacity = function() {
            var rand = Math.random(0,1);
            for (var i = 0; i < 100; i++) { // modify sine amplitude
                data[4].values[i].y = Math.sin(i/(5 + rand)) * .4 * rand - .25;
            }
            data[4].fillOpacity = rand;
            chart.update();
        };

        nv.addGraph(function() {
            chart = nv.models.lineChart()
                    .options({
                        duration: 300,
                        useInteractiveGuideline: true
                    })
                ;
            // chart sub-models (ie. xAxis, yAxis, etc) when accessed directly, return themselves, not the parent chart, so need to chain separately
            chart.xAxis
                    .axisLabel("Date (s)")
                    .tickFormat(function (d) { return d3.time.format('%b %d %Y')(new Date(d)); })
                    .staggerLabels(true)
                ;
            chart.yAxis
                    .axisLabel('Score (v)')
                    .tickFormat(function(d) {
                        if (d == null) {
                            return 'N/A';
                        }
                        return d3.format(',.2f')(d);
                    })
                ;
            data = residentData();
            d3.select('#chart2').append('svg')
                .datum(data)
                .call(chart);
            nv.utils.windowResize(chart.update);
            return chart;
        });

        function residentData() {
            var scores = [];
            //var answerList = $.getJSON("Statistics/GetQuestionData");
            
            var answerList;
            console.log("Hello");

            $.ajax({
                type: 'GET',
                data: 1,
                url: 'GetQuestionData',
                dataType: 'application/json',
                success: function(response) {
                    answerList = response;
                    console.log("Success!");
                },
                error: function(response) {
                    alert('Error during AJAX request');
                }
            });

      //      for (var i = 0; i <50; i++) {
      //          scores.push({ x: randomDate(new Date(2012, 0, 1), i*86400000), y: Math.random() * (5 - 1) + 1 });
      //      }

            //for (var i = 0; i < answerList.Answers.length; i++) {
            for (var i = 0; i < 50; i++) {
                //var answer = answerList.Answers[i];
                //var dateValue = answerList[i].Answers.y;
                //var formattedDate = new Date(parseInt(dateValue.replace("/Date(", "").replace(")/", ""), 10));
                //var score = answerlist.Answers[i].[x];
                scores.push({ x: 2, y: new Date(2012, 0, 1) });
            }

            return [
                {
                    area: true,
                    values: scores,
                    key: "Question 1 scores",
                    color: "#ff7f0e",
                    strokeWidth: 5
                }
            ];
        }*/



</script>
    }